language: java
jdk:
    - openjdk8
    
cache:
    directories: 
              - "$HOME/.cache"
jobs:
   - stage: deploy
     name: "Deploy stage"
     script:
          - mvn clean install
          - cp .travis.settings.xml $HOME/.m2/settings.xml
          - mvn deploy -DmuleDeploy
     if: branch = dev