language: java
jdk:
    - openjdk8
    
cache:
    directories: 
              - "$HOME/.cache"
jobs:
   - stage: deploy
     name: "Deploy stage"
     script:
          - mvn clean install
          - mvn deploy -DmuleDeploy -Dusername=apiseroCheck -Dpwd=Maya@128125
     if: branch = dev