language: java
jdk:
    - openjdk8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
jobs:
   - stage: deploy
     name: "Deploy stage"
     script:
          - mvn clean install
          - mvn deploy -DmuleDeploy -Dusername=${username} -Dpwd=${pwd}
     if: branch = dev #